home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('jadwal/<jadwal_id>', views.liat, name = 'jadwal'),
    path('delete/<jadwal_id>', views.delete, name = 'delete')
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    kelas = models.CharField(max_length = 40) 
    deskripsi = models.TextField(default='')
    dosen = models.CharField(max_length = 40, default='') 
    ruang_kelas = models.CharField(max_length = 40, default='')
    jumlah_sks = models.IntegerField(default=3)
    tahun_ajaran = models.CharField(max_length = 40, default='')
    
    def __str__(self):
        return self.kelas
    

home/forms.py
from django import forms
from .models import Jadwal

##class JadwalForm(forms.Form):
    ##jadwal = forms.CharField(max_length=40,
    ##widget=forms.TextInput(
    ##    attrs={ 'class' : 'form-control', 'aria-describedby' : 'emailHelp', 'placeholder' : 'Masukkan Jadwal Kelas'}
    ##))
    
class JadwalForm(forms.ModelForm):
    

    class Meta:
        model = Jadwal
        fields = ['kelas', 'deskripsi', 'dosen', 'ruang_kelas','jumlah_sks', 'tahun_ajaran']
        pilihan_tahun_ajaran = [
        ('Gasal 2019/2020', 'Gasal 2019/2020'),
        ('Genap 2019/2020', 'Genap 2019/2020'),
        ('Gasal 2020/2021', 'Gasal 2020/2021'),
        ('Genap 2020/2021', 'Genap 2020/2021')
    ]

        widgets={
            'kelas' : forms.TextInput(attrs={ 'class' : 'form-control', 'aria-describedby' : 'emailHelp', 'placeholder' : 'Masukkan Jadwal Kelas'}),
            'deskripsi' : forms.TextInput(attrs={'class' : 'form-control',  'placeholder' : 'Apa yang ada di dalam mata kuliah ini?'}),
            'dosen' : forms.TextInput(attrs={'class' : 'form-control',  'placeholder' : 'Siapa dosenmu?'}),
            'ruang_kelas' : forms.TextInput(attrs={'class' : 'form-control',  'placeholder' : 'Ruang berapa?'}),
            'jumlah_sks' : forms.TextInput(attrs={'class' : 'form-control',  'placeholder' : 'Jumlah sks'}),
            'tahun_ajaran' : forms.Select(choices=pilihan_tahun_ajaran)
        }

home/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from .models import Jadwal
from .forms import JadwalForm
# Create your views here.

def index(request):
    jadwal_kelas = Jadwal.objects.order_by('id')
    
    form = JadwalForm()

    context = {'jadwal_kelas' : jadwal_kelas, 'form' : form}
    
    if request.method == 'POST':
        form = JadwalForm(request.POST)

        if form.is_valid():
            new_jadwal = form.save()
            new_jadwal.save()

            return redirect('home:index')
        
    return render(request, 'home/index.html', context)

def liat(request, jadwal_id):
    jadwalnya = Jadwal.objects.get(id=jadwal_id)
    context = {'jadwalnya' : jadwalnya}
    return render(request, 'home/jadwal.html', context)

def delete(request, jadwal_id):
    Jadwal.objects.get(id=jadwal_id).delete()
    return redirect('home:index')

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Tambah SKS</title>
</head>

<body>
    <div>
    <h1>Yuk Tambah SKS!</h1>
    <form action="{% url 'home:index' %}" method="POST" role="form">
        {% csrf_token %}
        <div class="form-group">
          {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>

    <div>
      <ul>
        {% for nama in jadwal_kelas %}
        <a href = "{% url 'home:jadwal' nama.id %}"><li class="jadwal">{{ nama.kelas }}
          <a href="{% url 'home:delete' nama.id %}"><button class="delete btn btn-primary">Delete</button></a>
        </li></a><br><br><br>
        {% endfor %}
      </ul>
    </div>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/jadwal.html
{% load static %}

<head>
    <title>{{ jadwalnya.kelas}}</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
</head>

<body>
    <label class="detail">Nama : {{ jadwalnya.kelas}} <br></label>
    <label class="detail">Deskripsi : {{ jadwalnya.deskripsi}} <br></label>
    <label class="detail">Dosen : {{ jadwalnya.dosen }} <br></label>
    <label class="detail">Ruang Kelas : {{ jadwalnya.ruang_kelas }} <br></label>
    <label class="detail">Jumlah SKS : {{ jadwalnya.jumlah_sks }} <br></label>
    <label class="detail">Tahun Ajaran : {{ jadwalnya.tahun_ajaran }} <br></label>
</body>